### ISSUE TITLE
Should we allow compressing an empty string?

### ISSUE THREAD

**Issue by springmeyer** [mapbox/gzip-hpp#17]
Currently the API allows for compressing an empty string without throwing. It results in a compressed string that is `20` chars long. Should we continue to support this? Or should we catch this case and throw (since this usage is likely a programmer mistake)?

/cc @mapbox/core-tech

**Comment by joto** [comment]
If this is a programmer error somebody will soon notice that there is no data and fix it. If, on the other hand, there really is no data for some reason, throwing would be surprising. What would you expect the user of the lib should do if this throws?

**Comment by GretaCB** [comment]
Would there be any potential usecase for passing in a null string? 

This reminds me of some of the philosophy behind unpacker: Transparently process data. Take the input exactly as it is, without assumptions, and output based on what was given. Riding that wave for a sec in this situation: would throwing on a null string be making an unnecessary assumption?

**Comment by joto** [comment]
If you want to allow any input, surely the null string input is a possibility that needs to be handled. This could easily happen if you have, say, a bunch of vector tiles and some happen to be empty because there is no data for these files. Yes, ideally those files are not generated then, but if they are, you want the process munching through the bunch of files to not fail but keep going. Also you don't know at that level whether whatever you are working on will be able to handle missing files.

**Comment by springmeyer** [comment]
> Transparently process data
> you want the process munching through the bunch of files to not fail but keep going

Really enjoying this discussion. Both of your thoughts indicate to me that our current behavior is good and that we should document the fact that we don't warn or throw on empty strings. This way users that read our docs will consider this case and handle it before calling our API, in the way they need to. 👍  ?

**Comment by springmeyer** [comment]
Reflecting that this behavior is coming from zlib rather than gzip-hpp, so I'm no longer certain it is critical to document explicitly in this repo. Closing.
